### ISSUE TITLE
领取 分享 任务

### ISSUE THREAD

**Issue by liuyingbin1922** [vueClub/milk-vue#43]
1.申请认领分享组件任务
  
2.预计pr周期5天 (注意实际pr时间超出预期*2且没有任何说明,此任务将会被注销重新分配)

**Comment by febobo** [comment]
复复的任务

**Comment by liuyingbin1922** [comment]
because i just started learning vue  , and i  think i can hardly finish the issue , so i need to improve my ability . If i can not finish it , i say "sorry" first . 





------------------ 原始邮件 ------------------
发件人: "十三把刀";<notifications@github.com>;
发送时间: 2018年1月25日(星期四) 上午10:43
收件人: "vueClub/milk-vue"<milk-vue@noreply.github.com>;
抄送: "算1 刘颖斌"<212164693@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vueClub/milk-vue] 领取 分享 任务 (#43)




复复的任务

**Comment by febobo** [comment]
The share task you chose has been repeated, so I choose to close it, and you can choose a task to do in [https://github.com/vueClub/milk-vue/projects/1](https://github.com/vueClub/milk-vue/projects/1).

**Comment by liuyingbin1922** [comment]
now i got it  , thanks for telling me . 






------------------ 原始邮件 ------------------
发件人: "十三把刀";<notifications@github.com>;
发送时间: 2018年1月25日(星期四) 上午10:55
收件人: "vueClub/milk-vue"<milk-vue@noreply.github.com>;
抄送: "算1 刘颖斌"<212164693@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [vueClub/milk-vue] 领取 分享 任务 (#43)




The share task you chose has been repeated, so I choose to close it, and you can choose a task to do in https://github.com/vueClub/milk-vue/projects/1.
